spring.application.name=duaratrust
spring.datasource.url=jdbc:postgresql://localhost:5432/duaratrust
spring.datasource.username=postgres
spring.datasource.password=40119576
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8082
